[project]
name = "medlemsrapportering"
version = "0.1.0"
description = "Medlemsrapportering og etterarbeid"
readme = "README.md"
authors = [
    { name = "Craftsman Digital", email = "htcjon@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "fastexcel",
    "polars",
    "utilities",
    "xlsxwriter",
]

[tool.uv]
package = false

[tool.uv.sources]
utilities = { git = "https://github.com/samfunnet/utilities" }
